In [24]:
#https://archive.ics.uci.edu/ml/datasets/Heart+Disease
#supervised learning
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
columns = ["age","sex","cp","trestbps","chol","fbs","restecg","thalach","exang","oldpeak","slope","ca","thal","num"]
df = pd.read_csv("processed.switzerland.data", names = columns)
df.head(10)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,32,1,1,95,0,?,0,127,0,.7,1,?,?,1
1,34,1,4,115,0,?,?,154,0,.2,1,?,?,1
2,35,1,4,?,0,?,0,130,1,?,?,?,7,3
3,36,1,4,110,0,?,0,125,1,1,2,?,6,1
4,38,0,4,105,0,?,0,166,0,2.8,1,?,?,2
5,38,0,4,110,0,0,0,156,0,0,2,?,3,1
6,38,1,3,100,0,?,0,179,0,-1.1,1,?,?,0
7,38,1,3,115,0,0,0,128,1,0,2,?,7,1
8,38,1,4,135,0,?,0,150,0,0,?,?,3,2
9,38,1,4,150,0,?,0,120,1,?,?,?,3,1

In [25]:
df["age"].unique()

array([32, 34, 35, 36, 38, 40, 41, 42, 43, 45, 46, 47, 48, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       72, 73, 74], dtype=int64)

In [26]:
df.shape

(123, 14)

In [27]:
df.describe()

              age         sex          cp   chol         num
count  123.000000  123.000000  123.000000  123.0  123.000000
mean    55.317073    0.918699    3.699187    0.0    1.804878
std      9.032108    0.274414    0.688726    0.0    1.013503
min     32.000000    0.000000    1.000000    0.0    0.000000
25%     51.000000    1.000000    4.000000    0.0    1.000000
50%     56.000000    1.000000    4.000000    0.0    2.000000
75%     61.500000    1.000000    4.000000    0.0    3.000000
max     74.000000    1.000000    4.000000    0.0    4.000000

In [28]:
df.values

array([[32, 1, 1, ..., '?', '?', 1],
       [34, 1, 4, ..., '?', '?', 1],
       [35, 1, 4, ..., '?', '7', 3],
       ...,
       [72, 1, 3, ..., '2', '?', 0],
       [73, 0, 3, ..., '?', '3', 1],
       [74, 1, 2, ..., '?', '?', 1]], dtype=object)

In [31]:
x = df.drop(columns = ["thalach"])
y = df["thalach"]
model = DecisionTreeClassifier()
model.fit(x.values, y.values)
p = model.predict([#input what you want to predict])
p

ValueError: could not convert string to float: '?'